# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(max_length=75)),
                ('date_sub', models.DateField(blank=True)),
                ('date_conf', models.DateField(blank=True)),
                ('date_unsub', models.DateField(blank=True)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Email addres',
                'verbose_name_plural': 'Emails address',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('link', models.CharField(blank=True, max_length=250)),
                ('slug', models.CharField(max_length=50)),
                ('icon', models.CharField(choices=[(b'fb', b'facebook'), (b'vk', b'vkontakte'), (b'ok', b'odnoklassniki'), (b'yt', b'youtube'), (b'in', b'instagram'), (b'tw', b'twitter'), (b'lj', b'livejournul')], max_length=25)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('second_color', models.CharField(blank=True, max_length=7)),
                ('klass', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Social network',
                'verbose_name_plural': 'Social networks',
            },
        ),
        migrations.CreateModel(
            name='TypeLatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_link', models.CharField(blank=True, max_length=250)),
                ('comment', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('template', models.CharField(choices=[(b'thanks', b'latter/thanks.html'), (b'subscribe', b'latter/subscribe.html'), (b'lottery', b'latter/lottery.html'), (b'competition', b'latter/'), (b'buy_week', b'latter/buy_week.html'), (b'buy_two_week', b'latter/buy_two_week.html'), (b'buy_mother', b'latter/buy_mother.html'), (b'buy', b'latter/buy.html'), (b'bonus', b'latter/bonus.html')], max_length=25)),
                ('viseble', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Mailing',
            },
        ),
        migrations.AddField(
            model_name='latter',
            name='type',
            field=models.ManyToManyField(to='social.TypeLatter'),
        ),
    ]
