# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(choices=[(b'Carousel in post', b'carousel-in-post'), (b'Slider in post', b'slider-in-post'), (b'Slider on page', b'slider-on-page'), (b'Carousel on page', b'carousel-on-page')], max_length=50)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('pic', models.ImageField(blank=True, upload_to=b'storage/img/standart')),
                ('mini_pic', models.ImageField(blank=True, upload_to=b'storage/img/mini')),
                ('orig_pic', models.ImageField(blank=True, upload_to=b'storage/img/origenal')),
                ('date', models.DateField()),
                ('albom', models.ManyToManyField(blank=True, to='gallery.Album')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('link', models.CharField(blank=True, max_length=256)),
                ('promo_pix', models.CharField(blank=True, max_length=256)),
                ('code', models.TextField(blank=True)),
                ('image', models.ManyToManyField(to='gallery.Image')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
